/* Generated by web/scripts/gen-types.mjs from schema/*.schema.json. Do not edit:
 * change src/mustafatron/contract.py, then run `uv run mustafatron schema && npm run types`. */

/**
 * Published files by schema name (seasons/{year}.json all share `season`).
 */
export interface ContractFiles {
  games: GamesFile;
  h2h: H2HFile;
  managers: ManagersFile;
  meta: Meta;
  records: RecordsFile;
  season: SeasonFile;
  standings: StandingsFile;
}
/**
 * Every final game, all seasons, plus the current season's unplayed schedule.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GamesFile".
 */
export interface GamesFile {
  columns: string[];
  games: [number, number, number, string, string, number, number, string | null][];
  schema_version: 1;
  /**
   * tier column values index into this
   */
  tiers: string[];
  upcoming: [number, number, string, string][];
  upcoming_columns: string[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "H2HFile".
 */
export interface H2HFile {
  pairs: PairOut[];
  schema_version: 1;
}
/**
 * One all-time series, from manager ``a``'s side (``a`` < ``b`` alphabetically).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PairOut".
 */
export interface PairOut {
  a: string;
  b: string;
  blowout: MeetingOut;
  closest: MeetingOut;
  current_streak: StreakOut;
  flags: FlagOut[];
  games: number;
  last_meeting: MeetingOut;
  longest_streak_a: number;
  longest_streak_b: number;
  losses: number;
  playoff_losses: number;
  playoff_wins: number;
  points_against: number;
  points_for: number;
  /**
   * W/L/T from a's side, oldest meeting first
   */
  results: string;
  /**
   * Enough meetings to count as a rivalry (league_rules.yml)
   */
  rivalry: boolean;
  ties: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "MeetingOut".
 */
export interface MeetingOut {
  /**
   * Manager b's score
   */
  opponent_score: number;
  /**
   * Manager a's score
   */
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StreakOut".
 */
export interface StreakOut {
  /**
   * null when the last meeting was a tie
   */
  holder: string | null;
  length: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "FlagOut".
 */
export interface FlagOut {
  holder: string | null;
  kind: "streak" | "lopsided" | "dead_even";
  losses: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagersFile".
 */
export interface ManagersFile {
  managers: ManagerOut[];
  schema_version: 1;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagerOut".
 */
export interface ManagerOut {
  first_season: number;
  id: string;
  /**
   * null while still in the league
   */
  last_season: number | null;
  name: string;
  /**
   * Seasons with a team, from the published data
   */
  seasons: number[];
  short_name: string;
}
/**
 * What was published: seasons covered and where the current season stands.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
  current_season: number;
  current_season_finished: boolean;
  /**
   * Latest week of the current season with every game final
   */
  last_completed_week: number | null;
  league_name: string;
  schema_version: 1;
  seasons: number[];
  /**
   * Next week of the current season with games still to play
   */
  upcoming_week: number | null;
}
/**
 * Top 10 of each record. Single-game records count one-week matchups only.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "RecordsFile".
 */
export interface RecordsFile {
  game_records: {
    [k: string]: GameMarkOut[];
  };
  schema_version: 1;
  season_records: {
    [k: string]: SeasonMarkOut[];
  };
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GameMarkOut".
 */
export interface GameMarkOut {
  manager: string;
  opponent: string;
  opponent_score: number;
  playoff: boolean;
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonMarkOut".
 */
export interface SeasonMarkOut {
  losses: number;
  manager: string;
  points_for: number;
  season: number;
  ties: number;
  value: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonFile".
 */
export interface SeasonFile {
  champion: string | null;
  columns: string[];
  finished: boolean;
  /**
   * Every game this season, final or not
   */
  games: [number, number, number, string, string, number, number, string | null][];
  schema_version: 1;
  season: number;
  settings: SeasonSettingsOut;
  /**
   * Final standings order once finished, else by seed
   */
  teams: TeamOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonSettingsOut".
 */
export interface SeasonSettingsOut {
  final_week: number;
  playoff_team_count: number;
  points_per_reception: number;
  regular_season_weeks: number;
  team_count: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TeamOut".
 */
export interface TeamOut {
  abbrev: string;
  acquisitions: number;
  co_managers: string[];
  final_rank: number | null;
  losses: number;
  manager: string;
  name: string;
  playoff_seed: number;
  points_against: number;
  points_for: number;
  team_id: number;
  ties: number;
  trades: number;
  wins: number;
}
/**
 * All-time standings, best regular season win percentage first.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StandingsFile".
 */
export interface StandingsFile {
  schema_version: 1;
  standings: CareerOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CareerOut".
 */
export interface CareerOut {
  avg_finish: number | null;
  best_finish: number | null;
  championships: number;
  losses: number;
  manager: string;
  /**
   * Career winnings in multiples of the buy-in
   */
  net_payout: number;
  playoff_appearances: number;
  points_against: number;
  points_for: number;
  runner_ups: number;
  seasons: number;
  third_places: number;
  ties: number;
  win_pct: number;
  wins: number;
}
