/* Generated by web/scripts/gen-types.mjs from schema/*.schema.json. Do not edit:
 * change src/mustafatron/contract.py, then run `uv run mustafatron schema && npm run types`. */

/**
 * Published files by schema name (seasons/{year}.json all share `season`).
 */
export interface ContractFiles {
  games: GamesFile;
  h2h: H2HFile;
  managers: ManagersFile;
  meta: Meta;
  records: RecordsFile;
  season: SeasonFile;
  standings: StandingsFile;
}
/**
 * Every final game, all seasons, plus the current season's unplayed schedule.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GamesFile".
 */
export interface GamesFile {
  columns: string[];
  games: [number, number, number, string, string, number, number, string | null][];
  schema_version: 1;
  /**
   * tier column values index into this
   */
  tiers: string[];
  upcoming: [number, number, string, string][];
  upcoming_columns: string[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "H2HFile".
 */
export interface H2HFile {
  /**
   * Rivalries (a, b), closest to .500 first: abs(0.5 - win_pct), then most meetings
   */
  most_competitive: [string, string][];
  pairs: PairOut[];
  schema_version: 1;
}
/**
 * One all-time series, from manager ``a``'s side (``a`` < ``b`` alphabetically).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PairOut".
 */
export interface PairOut {
  a: string;
  /**
   * a's average margin; negative when b outscores a
   */
  avg_margin: number;
  /**
   * b's average score
   */
  avg_opponent_score: number;
  /**
   * a's average score
   */
  avg_score: number;
  b: string;
  blowout: MeetingOut;
  closest: MeetingOut;
  current_streak: StreakOut;
  flags: FlagOut[];
  games: number;
  /**
   * Last five results from a's side, oldest to newest
   */
  last_five: string;
  last_meeting: MeetingOut;
  longest_streak_a: number;
  longest_streak_b: number;
  losses: number;
  playoff_losses: number;
  playoff_wins: number;
  points_against: number;
  points_for: number;
  /**
   * W/L/T from a's side, oldest meeting first
   */
  results: string;
  /**
   * Enough meetings to count as a rivalry (league_rules.yml)
   */
  rivalry: boolean;
  ties: number;
  /**
   * a's share of the series, ties counting half
   */
  win_pct: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "MeetingOut".
 */
export interface MeetingOut {
  /**
   * Manager b's score
   */
  opponent_score: number;
  /**
   * Manager a's score
   */
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StreakOut".
 */
export interface StreakOut {
  /**
   * null when the last meeting was a tie
   */
  holder: string | null;
  length: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "FlagOut".
 */
export interface FlagOut {
  holder: string | null;
  kind: "streak" | "lopsided" | "dead_even";
  losses: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagersFile".
 */
export interface ManagersFile {
  managers: ManagerOut[];
  schema_version: 1;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagerOut".
 */
export interface ManagerOut {
  first_season: number;
  id: string;
  /**
   * null while still in the league
   */
  last_season: number | null;
  name: string;
  /**
   * Seasons with a team, from the published data
   */
  seasons: number[];
  short_name: string;
}
/**
 * What was published: seasons covered and where the current season stands.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
  current_season: number;
  current_season_finished: boolean;
  /**
   * Latest week of the current season with every game final
   */
  last_completed_week: number | null;
  league_name: string;
  schema_version: 1;
  seasons: number[];
  /**
   * Next week of the current season with games still to play
   */
  upcoming_week: number | null;
}
/**
 * Top 10 of each record, best first.
 *
 * Game and matchup records count one-week matchups only; week records are per NFL week, league-wide;
 * season records count finished seasons; streaks are regular season games (see stats/records.py).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "RecordsFile".
 */
export interface RecordsFile {
  game_records: {
    [k: string]: GameMarkOut[];
  };
  matchup_records: {
    [k: string]: MatchupMarkOut[];
  };
  schema_version: 1;
  season_records: {
    [k: string]: SeasonMarkOut[];
  };
  streak_records: {
    [k: string]: StreakMarkOut[];
  };
  week_records: {
    [k: string]: WeekMarkOut[];
  };
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GameMarkOut".
 */
export interface GameMarkOut {
  manager: string;
  opponent: string;
  opponent_score: number;
  playoff: boolean;
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "MatchupMarkOut".
 */
export interface MatchupMarkOut {
  away: string;
  away_score: number;
  home: string;
  home_score: number;
  playoff: boolean;
  season: number;
  total: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonMarkOut".
 */
export interface SeasonMarkOut {
  losses: number;
  manager: string;
  points_for: number;
  season: number;
  ties: number;
  value: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StreakMarkOut".
 */
export interface StreakMarkOut {
  /**
   * Still running: includes the manager's latest regular season game
   */
  active: boolean;
  end_season: number;
  end_week: number;
  length: number;
  manager: string;
  start_season: number;
  start_week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeekMarkOut".
 */
export interface WeekMarkOut {
  /**
   * NFL week
   */
  period: number;
  season: number;
  teams: number;
  /**
   * Every team's points that NFL week
   */
  total: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonFile".
 */
export interface SeasonFile {
  champion: string | null;
  columns: string[];
  finished: boolean;
  /**
   * Every game this season, final or not
   */
  games: [number, number, number, string, string, number, number, string | null][];
  /**
   * NFL weeks with scores so far, in order
   */
  periods: number[];
  /**
   * First NFL week of the playoffs
   */
  playoff_start_period: number | null;
  schema_version: 1;
  season: number;
  settings: SeasonSettingsOut;
  superlatives: SuperlativeOut[];
  /**
   * Final standings order once finished, else by seed
   */
  teams: TeamOut[];
  /**
   * Same order as teams
   */
  weekly: WeeklyOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonSettingsOut".
 */
export interface SeasonSettingsOut {
  final_week: number;
  playoff_team_count: number;
  points_per_reception: number;
  regular_season_weeks: number;
  team_count: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SuperlativeOut".
 */
export interface SuperlativeOut {
  key:
    | "high_week"
    | "low_week"
    | "most_points"
    | "fewest_points"
    | "most_points_against"
    | "best_all_play"
    | "luckiest"
    | "unluckiest";
  manager: string;
  /**
   * NFL week, for single-week superlatives
   */
  period: number | null;
  /**
   * Points, or a win pct (best_all_play), or win pct minus all-play pct (luck)
   */
  value: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TeamOut".
 */
export interface TeamOut {
  abbrev: string;
  acquisitions: number;
  co_managers: string[];
  final_rank: number | null;
  losses: number;
  manager: string;
  name: string;
  playoff_seed: number;
  points_against: number;
  points_for: number;
  team_id: number;
  ties: number;
  trades: number;
  wins: number;
}
/**
 * One team's season, NFL week by NFL week.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeeklyOut".
 */
export interface WeeklyOut {
  all_play_losses: number;
  all_play_ties: number;
  /**
   * Regular season record against the whole league each week
   */
  all_play_wins: number;
  manager: string;
  /**
   * One character per period: W/L/T for a final one-week matchup, '-' otherwise
   */
  results: string;
  /**
   * Points per NFL week, aligned with SeasonFile.periods
   */
  scores: (number | null)[];
}
/**
 * All-time standings, best regular season win percentage first, and every finished season's podium.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StandingsFile".
 */
export interface StandingsFile {
  /**
   * Finished seasons, newest first
   */
  ledger: LedgerOut[];
  schema_version: 1;
  standings: CareerOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "LedgerOut".
 */
export interface LedgerOut {
  champion: string;
  champion_seed: number;
  last: string;
  /**
   * Most regular season points for
   */
  most_points: string;
  runner_up: string;
  season: number;
  third: string;
  /**
   * Best regular season record (playoff seed 1)
   */
  top_seed: string;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CareerOut".
 */
export interface CareerOut {
  avg_finish: number | null;
  /**
   * Regular season (points for - against) per game
   */
  avg_margin: number;
  best_finish: number | null;
  championships: number;
  /**
   * Seasons with a final rank; finishes and payouts count these
   */
  finished_seasons: number;
  last_places: number;
  losses: number;
  manager: string;
  /**
   * Career winnings in multiples of the buy-in
   */
  net_payout: number;
  playoff_appearances: number;
  playoff_losses: number;
  playoff_points_against: number;
  playoff_points_for: number;
  /**
   * Championship bracket games; consolation ladders excluded
   */
  playoff_wins: number;
  points_against: number;
  /**
   * Regular season
   */
  points_for: number;
  /**
   * net_payout per buy-in paid (finished seasons)
   */
  roi: number;
  runner_ups: number;
  seasons: number;
  third_places: number;
  ties: number;
  win_pct: number;
  /**
   * Regular season
   */
  wins: number;
  worst_finish: number | null;
}
