/* Generated by web/scripts/gen-types.mjs from schema/*.schema.json. Do not edit:
 * change src/mustafatron/contract.py, then run `uv run mustafatron schema && npm run types`. */

/**
 * Published files by schema name (seasons/{year}.json all share `season`).
 */
export interface ContractFiles {
  awards: AwardsFile;
  coaching: CoachingFile;
  draft: DraftFile;
  games: GamesFile;
  h2h: H2HFile;
  luck: LuckFile;
  managers: ManagersFile;
  meta: Meta;
  profiles: ProfilesFile;
  records: RecordsFile;
  season: SeasonFile;
  standings: StandingsFile;
  trades: TradesFile;
  week: WeekFile;
  weeks: WeeksFile;
}
/**
 * The league's awards and every season's winner (league_rules.yml says what decides each).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "AwardsFile".
 */
export interface AwardsFile {
  awards: AwardOut[];
  schema_version: 1;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "AwardOut".
 */
export interface AwardOut {
  description: string;
  id: string;
  name: string;
  /**
   * First season the data can decide it
   */
  since: number;
  status: "official" | "proposed";
  /**
   * Every finished season, newest first
   */
  winners: AwardWinnerOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "AwardWinnerOut".
 */
export interface AwardWinnerOut {
  detail: string;
  manager: string | null;
  season: number;
  /**
   * computed from the data, recorded by hand (data/manual/awards.yml), or not recorded
   */
  source: "computed" | "manual" | "unrecorded";
  /**
   * The metric: trade value, bench points, or luck in wins
   */
  value: number | null;
}
/**
 * Lineup decisions, from the first season ESPN kept weekly rosters (2018).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CoachingFile".
 */
export interface CoachingFile {
  /**
   * Perfect lineups, highest-scoring first, top 10
   */
  best_weeks: CoachingWeekOut[];
  /**
   * Fewest points left per week first
   */
  careers: CareerCoachingOut[];
  /**
   * First season with player-level lineups
   */
  first_season: number | null;
  /**
   * Losses the bench would have won, most points left first
   */
  if_only: IfOnlyOut[];
  schema_version: 1;
  /**
   * By season, fewest points left per week first
   */
  seasons: SeasonCoachingOut[];
  /**
   * Most points left on the bench, top 10
   */
  worst_weeks: CoachingWeekOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CoachingWeekOut".
 */
export interface CoachingWeekOut {
  actual: number;
  left_on_bench: number;
  manager: string;
  optimal: number;
  /**
   * NFL week
   */
  period: number;
  season: number;
  /**
   * Starters the best lineup benches
   */
  should_have_sat: PlayerPointsOut[];
  /**
   * Benched players the best lineup starts
   */
  should_have_started: PlayerPointsOut[];
  substitutions: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PlayerPointsOut".
 */
export interface PlayerPointsOut {
  name: string;
  points: number;
  position: string;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CareerCoachingOut".
 */
export interface CareerCoachingOut {
  /**
   * Points the starters scored
   */
  actual: number;
  /**
   * actual / optimal
   */
  efficiency: number;
  /**
   * optimal - actual
   */
  left_on_bench: number;
  manager: string;
  /**
   * Points the best possible lineups would have scored
   */
  optimal: number;
  /**
   * left_on_bench per week counted
   */
  per_week: number;
  perfect_weeks: number;
  seasons: number;
  /**
   * Lineup changes that would have made every week optimal
   */
  substitutions: number;
  /**
   * NFL weeks counted: regular season, championship bracket, 3rd place game
   */
  weeks: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "IfOnlyOut".
 */
export interface IfOnlyOut {
  left_on_bench: number;
  manager: string;
  opponent: string;
  opponent_score: number;
  /**
   * What the manager's best lineup would have scored
   */
  optimal: number;
  score: number;
  season: number;
  tier: string;
  /**
   * Matchup period
   */
  week: number;
  /**
   * One per NFL week of the matchup
   */
  weeks: CoachingWeekOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonCoachingOut".
 */
export interface SeasonCoachingOut {
  /**
   * Points the starters scored
   */
  actual: number;
  /**
   * actual / optimal
   */
  efficiency: number;
  /**
   * optimal - actual
   */
  left_on_bench: number;
  manager: string;
  /**
   * Points the best possible lineups would have scored
   */
  optimal: number;
  /**
   * left_on_bench per week counted
   */
  per_week: number;
  perfect_weeks: number;
  season: number;
  /**
   * Lineup changes that would have made every week optimal
   */
  substitutions: number;
  /**
   * NFL weeks counted: regular season, championship bracket, 3rd place game
   */
  weeks: number;
}
/**
 * Draft value, every finished season, keepers excluded. Each draft is valued against its own line.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "DraftFile".
 */
export interface DraftFile {
  best_drafts: DraftClassOut[];
  busts: PickValueOut[];
  busts_through_round: number;
  /**
   * Best average value per pick first
   */
  drafters: DrafterOut[];
  /**
   * Rounds 1 through this are 'early' (the bust cutoff)
   */
  early_rounds: number;
  first_season: number | null;
  rounds: RoundOut[];
  schema_version: 1;
  steals: PickValueOut[];
  steals_after_round: number;
  worst_drafts: DraftClassOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "DraftClassOut".
 */
export interface DraftClassOut {
  best: PickValueOut;
  manager: string;
  picks: number;
  season: number;
  value: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PickValueOut".
 */
export interface PickValueOut {
  /**
   * That season's line for this pick
   */
  expected: number;
  manager: string;
  overall_pick: number;
  player: string;
  /**
   * The player's season in this league's scoring
   */
  points: number;
  /**
   * Points minus the mean of drafted players at his position
   */
  points_above_avg: number;
  position: string;
  round: number;
  round_pick: number;
  season: number;
  /**
   * points_above_avg - expected: points above what the pick promised
   */
  value: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "DrafterOut".
 */
export interface DrafterOut {
  /**
   * Rounds 1 through DraftFile.early_rounds
   */
  early_per_pick: number;
  early_picks: number;
  late_per_pick: number;
  late_picks: number;
  manager: string;
  per_pick: number;
  picks: number;
  seasons: number;
  value: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "RoundOut".
 */
export interface RoundOut {
  avg_points: number;
  /**
   * Average value per pick in this round, by manager
   */
  by_manager: {
    [k: string]: number;
  };
  picks: number;
  round: number;
}
/**
 * Every final game, all seasons, plus the current season's unplayed schedule.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GamesFile".
 */
export interface GamesFile {
  columns: string[];
  games: [number, number, number, string, string, number, number, string | null][];
  schema_version: 1;
  /**
   * tier column values index into this
   */
  tiers: string[];
  upcoming: [number, number, string, string][];
  upcoming_columns: string[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "H2HFile".
 */
export interface H2HFile {
  /**
   * Rivalries (a, b), closest to .500 first: abs(0.5 - win_pct), then most meetings
   */
  most_competitive: [string, string][];
  pairs: PairOut[];
  schema_version: 1;
}
/**
 * One all-time series, from manager ``a``'s side (``a`` < ``b`` alphabetically).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PairOut".
 */
export interface PairOut {
  a: string;
  /**
   * a's average margin; negative when b outscores a
   */
  avg_margin: number;
  /**
   * b's average score
   */
  avg_opponent_score: number;
  /**
   * a's average score
   */
  avg_score: number;
  b: string;
  blowout: MeetingOut;
  closest: MeetingOut;
  current_streak: StreakOut;
  flags: FlagOut[];
  games: number;
  /**
   * Last five results from a's side, oldest to newest
   */
  last_five: string;
  last_meeting: MeetingOut;
  longest_streak_a: number;
  longest_streak_b: number;
  losses: number;
  playoff_losses: number;
  playoff_wins: number;
  points_against: number;
  points_for: number;
  /**
   * W/L/T from a's side, oldest meeting first
   */
  results: string;
  /**
   * Enough meetings to count as a rivalry (league_rules.yml)
   */
  rivalry: boolean;
  ties: number;
  /**
   * a's share of the series, ties counting half
   */
  win_pct: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "MeetingOut".
 */
export interface MeetingOut {
  /**
   * Manager b's score
   */
  opponent_score: number;
  /**
   * Manager a's score
   */
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StreakOut".
 */
export interface StreakOut {
  /**
   * null when the last meeting was a tie
   */
  holder: string | null;
  length: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "FlagOut".
 */
export interface FlagOut {
  holder: string | null;
  kind: "streak" | "lopsided" | "dead_even";
  losses: number;
  wins: number;
}
/**
 * All-play records and luck: careers, every team-season, and the luckiest and unluckiest seasons.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "LuckFile".
 */
export interface LuckFile {
  /**
   * Record most overstated (luck_wins) first
   */
  careers: CareerLuckOut[];
  /**
   * Finished seasons, by luck, top 10
   */
  luckiest: SeasonLuckOut[];
  schema_version: 1;
  /**
   * Every team-season, oldest first
   */
  seasons: SeasonLuckOut[];
  /**
   * Finished seasons, by luck, bottom 10
   */
  unluckiest: SeasonLuckOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CareerLuckOut".
 */
export interface CareerLuckOut {
  all_play_losses: number;
  all_play_pct: number;
  all_play_ties: number;
  /**
   * Against every other team, every final regular season week
   */
  all_play_wins: number;
  losses: number;
  /**
   * win_pct - all_play_pct: positive means the schedule was kind
   */
  luck: number;
  /**
   * Actual wins minus wins at the all-play rate over the same games
   */
  luck_wins: number;
  manager: string;
  seasons: number;
  ties: number;
  win_pct: number;
  /**
   * Regular season
   */
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonLuckOut".
 */
export interface SeasonLuckOut {
  all_play_losses: number;
  all_play_pct: number;
  all_play_ties: number;
  /**
   * Against every other team, every final regular season week
   */
  all_play_wins: number;
  final_rank: number | null;
  finished: boolean;
  losses: number;
  /**
   * win_pct - all_play_pct: positive means the schedule was kind
   */
  luck: number;
  /**
   * Actual wins minus wins at the all-play rate over the same games
   */
  luck_wins: number;
  manager: string;
  season: number;
  ties: number;
  win_pct: number;
  /**
   * Regular season
   */
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagersFile".
 */
export interface ManagersFile {
  managers: ManagerOut[];
  schema_version: 1;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ManagerOut".
 */
export interface ManagerOut {
  first_season: number;
  id: string;
  /**
   * null while still in the league
   */
  last_season: number | null;
  name: string;
  /**
   * Seasons with a team, from the published data
   */
  seasons: number[];
  short_name: string;
}
/**
 * What was published: seasons covered and where the current season stands.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
  current_season: number;
  current_season_finished: boolean;
  /**
   * Latest week of the current season with every game final
   */
  last_completed_week: number | null;
  league_name: string;
  schema_version: 1;
  seasons: number[];
  /**
   * Next week of the current season with games still to play
   */
  upcoming_week: number | null;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ProfilesFile".
 */
export interface ProfilesFile {
  profiles: ProfileOut[];
  schema_version: 1;
}
/**
 * What a manager's page needs beyond standings.json, seasons/*.json and h2h.json.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "ProfileOut".
 */
export interface ProfileOut {
  all_play_losses: number;
  all_play_ties: number;
  /**
   * Career regular season record against the whole league each week
   */
  all_play_wins: number;
  /**
   * Highest single NFL weeks, best first
   */
  best_weeks: WeekLineOut[];
  manager: string;
  /**
   * Lowest single NFL weeks, worst first
   */
  worst_weeks: WeekLineOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeekLineOut".
 */
export interface WeekLineOut {
  opponent: string;
  /**
   * NFL week
   */
  period: number;
  points: number;
  /**
   * null for half of a two-week playoff matchup
   */
  result: ("W" | "L" | "T") | null;
  season: number;
}
/**
 * Top 10 of each record, best first.
 *
 * Game and matchup records count one-week matchups only; week records are per NFL week, league-wide;
 * season records count finished seasons; streaks are regular season games (see stats/records.py).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "RecordsFile".
 */
export interface RecordsFile {
  game_records: {
    [k: string]: GameMarkOut[];
  };
  matchup_records: {
    [k: string]: MatchupMarkOut[];
  };
  schema_version: 1;
  season_records: {
    [k: string]: SeasonMarkOut[];
  };
  streak_records: {
    [k: string]: StreakMarkOut[];
  };
  week_records: {
    [k: string]: WeekMarkOut[];
  };
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "GameMarkOut".
 */
export interface GameMarkOut {
  manager: string;
  opponent: string;
  opponent_score: number;
  playoff: boolean;
  score: number;
  season: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "MatchupMarkOut".
 */
export interface MatchupMarkOut {
  away: string;
  away_score: number;
  home: string;
  home_score: number;
  playoff: boolean;
  season: number;
  total: number;
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonMarkOut".
 */
export interface SeasonMarkOut {
  losses: number;
  manager: string;
  points_for: number;
  season: number;
  ties: number;
  value: number;
  wins: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StreakMarkOut".
 */
export interface StreakMarkOut {
  /**
   * Can still grow: includes the manager's latest regular season game, the manager is still in the league, and (one-season streaks) that season's regular season isn't over
   */
  active: boolean;
  end_season: number;
  end_week: number;
  length: number;
  manager: string;
  start_season: number;
  start_week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeekMarkOut".
 */
export interface WeekMarkOut {
  /**
   * NFL week
   */
  period: number;
  season: number;
  teams: number;
  /**
   * Every team's points that NFL week
   */
  total: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonFile".
 */
export interface SeasonFile {
  champion: string | null;
  columns: string[];
  finished: boolean;
  /**
   * Every game this season, final or not
   */
  games: [number, number, number, string, string, number, number, string | null][];
  /**
   * NFL weeks with scores so far, in order
   */
  periods: number[];
  /**
   * First NFL week of the playoffs
   */
  playoff_start_period: number | null;
  schema_version: 1;
  season: number;
  settings: SeasonSettingsOut;
  superlatives: SuperlativeOut[];
  /**
   * Final standings order once finished, else by seed
   */
  teams: TeamOut[];
  /**
   * Same order as teams
   */
  weekly: WeeklyOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SeasonSettingsOut".
 */
export interface SeasonSettingsOut {
  final_week: number;
  playoff_team_count: number;
  points_per_reception: number;
  regular_season_weeks: number;
  team_count: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "SuperlativeOut".
 */
export interface SuperlativeOut {
  key:
    | "high_week"
    | "low_week"
    | "most_points"
    | "fewest_points"
    | "most_points_against"
    | "best_all_play"
    | "luckiest"
    | "unluckiest";
  manager: string;
  /**
   * NFL week, for single-week superlatives
   */
  period: number | null;
  /**
   * Points, or a win pct (best_all_play), or win pct minus all-play pct (luck)
   */
  value: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TeamOut".
 */
export interface TeamOut {
  abbrev: string;
  acquisitions: number;
  co_managers: string[];
  final_rank: number | null;
  losses: number;
  manager: string;
  name: string;
  playoff_seed: number;
  points_against: number;
  points_for: number;
  team_id: number;
  ties: number;
  trades: number;
  wins: number;
}
/**
 * One team's season, NFL week by NFL week.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeeklyOut".
 */
export interface WeeklyOut {
  all_play_losses: number;
  all_play_ties: number;
  /**
   * Regular season record against the whole league each week
   */
  all_play_wins: number;
  manager: string;
  /**
   * One character per period: W/L/T for a final one-week matchup, '-' otherwise
   */
  results: string;
  /**
   * Points per NFL week, aligned with SeasonFile.periods
   */
  scores: (number | null)[];
}
/**
 * All-time standings, best regular season win percentage first, and every finished season's podium.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StandingsFile".
 */
export interface StandingsFile {
  /**
   * Finished seasons, newest first
   */
  ledger: LedgerOut[];
  schema_version: 1;
  standings: CareerOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "LedgerOut".
 */
export interface LedgerOut {
  champion: string;
  champion_seed: number;
  last: string;
  /**
   * Most regular season points for
   */
  most_points: string;
  runner_up: string;
  season: number;
  third: string;
  /**
   * Best regular season record (playoff seed 1)
   */
  top_seed: string;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "CareerOut".
 */
export interface CareerOut {
  avg_finish: number | null;
  /**
   * Regular season (points for - against) per game
   */
  avg_margin: number;
  best_finish: number | null;
  championships: number;
  /**
   * Seasons with a final rank; finishes and payouts count these
   */
  finished_seasons: number;
  last_places: number;
  losses: number;
  manager: string;
  /**
   * Career winnings in multiples of the buy-in
   */
  net_payout: number;
  playoff_appearances: number;
  playoff_losses: number;
  playoff_points_against: number;
  playoff_points_for: number;
  /**
   * Championship bracket games; consolation ladders excluded
   */
  playoff_wins: number;
  points_against: number;
  /**
   * Regular season
   */
  points_for: number;
  /**
   * net_payout per buy-in paid (finished seasons)
   */
  roi: number;
  runner_ups: number;
  seasons: number;
  third_places: number;
  ties: number;
  win_pct: number;
  /**
   * Regular season
   */
  wins: number;
  worst_finish: number | null;
}
/**
 * Every trade with its retrospective verdict (from 2018), and trade and add counts (every season).
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TradesFile".
 */
export interface TradesFile {
  /**
   * Sides that gained the most, top 10
   */
  best: TradeSideRefOut[];
  counts: TradeCountOut[];
  /**
   * First season with trade detail
   */
  first_season: number | null;
  /**
   * Trade ids, biggest margin first, top 10
   */
  lopsided: string[];
  schema_version: 1;
  /**
   * Finished seasons, oldest first
   */
  trades: TradeOut[];
  /**
   * Sides that lost the most, top 10
   */
  worst: TradeSideRefOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TradeSideRefOut".
 */
export interface TradeSideRefOut {
  manager: string;
  /**
   * TradeOut.id
   */
  trade: string;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TradeCountOut".
 */
export interface TradeCountOut {
  /**
   * Adds, ESPN's count
   */
  acquisitions: number;
  manager: string;
  season: number;
  /**
   * ESPN's count
   */
  trades: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TradeOut".
 */
export interface TradeOut {
  /**
   * ISO date ESPN recorded the acceptance, when it could be matched
   */
  date: string | null;
  id: string;
  /**
   * Winner's value minus loser's
   */
  margin: number;
  /**
   * First NFL week the players were on their new rosters
   */
  period: number;
  season: number;
  /**
   * Two sides, by manager id
   */
  sides: TradeSideOut[];
  winner: string;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "TradeSideOut".
 */
export interface TradeSideOut {
  manager: string;
  received: PlayerRefOut[];
  sent: PlayerRefOut[];
  /**
   * Points the trade added to this team's best lineups, rest of season
   */
  value: number;
  /**
   * Weeks valued: from the trade to the team's last game that mattered
   */
  weeks: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "PlayerRefOut".
 */
export interface PlayerRefOut {
  name: string;
  position: string;
}
/**
 * One weekly report, everything as it stood when the week ended ("through week N").
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeekFile".
 */
export interface WeekFile {
  columns: string[];
  /**
   * This week's games
   */
  games: [number, number, number, string, string, number, number, string | null][];
  label: string;
  /**
   * The NFL weeks this matchup week covers
   */
  periods: number[];
  playoff: boolean;
  schema_version: 1;
  season: number;
  /**
   * Regular season through this week, best record first; seed order in the playoffs
   */
  standings: StandingLineOut[];
  /**
   * Matchup period
   */
  week: number;
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "StandingLineOut".
 */
export interface StandingLineOut {
  losses: number;
  manager: string;
  points_against: number;
  points_for: number;
  ties: number;
  wins: number;
}
/**
 * Every weekly report, the archive the /week pages are built from.
 *
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeeksFile".
 */
export interface WeeksFile {
  /**
   * The latest report of the season in progress (the front page); null between seasons
   */
  current: WeekRefOut | null;
  schema_version: 1;
  /**
   * Every week with all its games final, oldest first
   */
  weeks: WeekRefOut[];
}
/**
 * This interface was referenced by `ContractFiles`'s JSON-Schema
 * via the `definition` "WeekRefOut".
 */
export interface WeekRefOut {
  /**
   * "Week 5", or the playoff round: "Semifinals", "Championship"
   */
  label: string;
  playoff: boolean;
  season: number;
  /**
   * Matchup period
   */
  week: number;
}
