// Generate src/types/contract.ts from the committed JSON Schemas in ../schema/.
//
//   npm run types          regenerate after `uv run mustafatron schema`
//   npm run types:check    fail if the committed file is stale (CI)
//
// The schemas come from the pydantic models in src/mustafatron/contract.py. Before compiling, they
// are merged into one document (so shared names are emitted once) and adjusted for reading
// published output rather than validating input:
//   - every field is required: publish writes defaulted fields too (model_dump_json)
//   - tuples (`prefixItems`, draft 2020-12) become fixed-length `items` arrays, which the compiler
//     understands
//   - per-field titles are dropped, so fields don't each get a named alias

import { readdir, readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

const SCHEMA_DIR = new URL("../../schema/", import.meta.url);
const OUT = new URL("../src/types/contract.ts", import.meta.url);

function adjust(node, isProperty = false) {
  if (Array.isArray(node)) return node.map((n) => adjust(n));
  if (node === null || typeof node !== "object") return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === "title" && isProperty) continue;
    if (k === "properties") {
      out.properties = Object.fromEntries(Object.entries(v).map(([p, s]) => [p, adjust(s, true)]));
    } else if (k === "prefixItems") {
      out.items = v.map((n) => adjust(n));
      out.minItems = out.maxItems = v.length;
      out.additionalItems = false;
    } else if (k === "default") {
      continue;
    } else {
      out[k] = adjust(v);
    }
  }
  if (out.properties) out.required = Object.keys(out.properties);
  if (out.type === "object" && out.properties && out.additionalProperties === undefined) {
    out.additionalProperties = false;
  }
  return out;
}

const files = (await readdir(SCHEMA_DIR)).filter((f) => f.endsWith(".schema.json")).sort();
const defs = {};
const roots = {};
for (const file of files) {
  const schema = JSON.parse(await readFile(new URL(file, SCHEMA_DIR), "utf8"));
  const { $defs = {}, ...root } = schema;
  for (const [name, def] of Object.entries($defs)) {
    if (defs[name] && JSON.stringify(defs[name]) !== JSON.stringify(def)) {
      throw new Error(`$defs/${name} differs between schema files`);
    }
    defs[name] = def;
  }
  defs[root.title] = root;
  roots[file.replace(".schema.json", "")] = { $ref: `#/$defs/${root.title}` };
}

const merged = adjust({
  title: "ContractFiles",
  description: "Published files by schema name (seasons/{year}.json all share `season`).",
  type: "object",
  properties: roots,
  $defs: defs,
});

const banner = `/* Generated by web/scripts/gen-types.mjs from schema/*.schema.json. Do not edit:
 * change src/mustafatron/contract.py, then run \`uv run mustafatron schema && npm run types\`. */`;
const ts = await compile(merged, "ContractFiles", {
  bannerComment: banner,
  additionalProperties: false,
  unreachableDefinitions: true,
  style: { printWidth: 110 },
});

if (process.argv.includes("--check")) {
  const current = await readFile(OUT, "utf8").catch(() => "");
  if (current.replace(/\r\n/g, "\n") !== ts) {
    console.error("web/src/types/contract.ts is stale: run `npm run types` in web/");
    process.exit(1);
  }
  console.log("web/src/types/contract.ts is current");
} else {
  await writeFile(OUT, ts);
  console.log(`wrote ${OUT.pathname}`);
}
